{"level":"error","service":"user-service"}
{"level":"error","service":"user-service"}
{"level":"error"}
{"level":"error"}
{"level":"error"}
{"level":"error","message":"La funcion se ejecutó pero presentó un error"}
{"level":"error","message":"La funcion se ejecutó pero presentó un error"}
{"level":"error","message":"La funcion se ejecutó pero presentó un error Esta funcion lanza siempre un error","stack":"Error: Esta funcion lanza siempre un error\n    at error (C:\\Users\\lui_s\\Curso-JavaScript\\new-project\\Ejercicio 9\\index.js:4:11)\n    at Object.<anonymous> (C:\\Users\\lui_s\\Curso-JavaScript\\new-project\\Ejercicio 9\\index.js:9:5)\n    at Module._compile (node:internal/modules/cjs/loader:1126:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)\n    at Module.load (node:internal/modules/cjs/loader:1004:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:839:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:17:47"}
